use super::Style;
use crate::attribute::ToAttribute;
use crate::{attribute::Attribute, AttributeGetter, PreBaseState, StyleBaseState};

simple_attr::define_attributes!(
align-content:stretch|center|flex-start|flex-end|space-between|space-around|space-evenly|initial|inherit;
align-items:stretch|center|flex-start|flex-end|start|end|baseline|initial|inherit;
position:static_|relative|fixed|absolute|sticky|initial|inherit;
align-self:auto|stretch|center|flex-start|flex-end|baseline|initial|inherit;
all:initial|inherit|unset;
box-decoration-break:slice|clone|initial|inherit|unset;
box-sizing:content-box|border-box|initial|inherit;
background-repeat:repeat-x|repeat-y|no-repeat|space|round|initial|inherit;
background-origin:padding-box|border-box|content-box|initial|inherit;
background-clip:padding-box|border-box|content-box|initial|inherit;
background-blend-mode:normal|multiply|screen|overlay|darken|lighten|color-dodge|saturation|color|luminosity;
background-attachment:scroll|fixed|local|initial|inherit;
animation-direction:normal|reverse|alternate|alternate-reverse|initial|inherit;
animation-fill-mode:none|forwards|backwards|both|initial|inherit;
animation-play-state:paused|running|initial|inherit;
backface-visibility:visible|hidden|initial|inherit;
border-block-end-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;
border-block-start-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;
border-collapse:separate|collapse|initial|inherit;
border-inline-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;
border-inline-start-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;
border-inline-end-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;
border-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;
border-left-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;
border-right-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;
border-top-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;
border-bottom-style:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|initial|inherit;
break-after:auto|all|always|avoid|avoid-column|avoid-page|avoid-region|column|left|page|recto|region|right|verso|initial|inherit;
break-before:auto|all|always|avoid|avoid-column|avoid-page|avoid-region|column|left|page|recto|region|right|verso|initial|inherit;
break-inside:auto|all|always|avoid|avoid-column|avoid-page|avoid-region|column|left|page|recto|region|right|verso|initial|inherit;
caption-side:top|bottom|initial|inherit;
clear:none|left|right|both|initial|inherit;
color-scheme:normal|light|dark|only;
);
