[package]
name = "simple_attr"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
ident_case = "1.0.1"
proc-macro2 = "1.0.86"
quote = "1.0.37"


[lib]
proc-macro = true
