[package]
name = "simple_attr"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
proc-macro-error2 = "2.0.1"
proc-macro2 = "1.0.86"
quote = "1.0.37"
